// Lista divinità da bestemmiare
const soggetti = [
    "Dio", "Gesù", "Cristo", "Madonna", "Spirito Santo", "Zeus",
    "San Pietro", "San Paolo", "San Gennaro", "San Giuseppe",
    "Sant’Antonio", "San Francesco", "Santa Maria", "Santa Chiara",
    "Trinità", "Papa", "Messia", "Signore", "Vaticano", "Radio Maria", "Maria", "Città del Vaticano"
];

// Lista aggettivi/nomi da attribuire alle divinità
const oggetti = [
    "Microsoft", "Google", "Kinder", "Kinder bueno", "GPT", "AI", "PowerPoint", "Microsoft Word", "PDF",
    "WiFi", "Router", "Mouse", "Webcam", "Cloud", "Bluetooth", "Auricolare",
    "Smartwatch", "SSD", "USB-C", "Cavo HDMI", "Stampante", "Tastiera",
    "Minecraft", "Crafting Table", "Joystick", "Meccanico", "Ingegnere", "Programmatore",
    "Panettiere", "Bagnino", "Barista", "Corriere", "Tatuatore", "Magazziniere", "Cameriere",
    "YouTuber", "Social Media Manager", "Forno Elettrico", "Carta Igienica", "Tram di Milano", "Boia", "Pixelato",
    "Casse Bluetooth", "Cucchiaio Sporco", "Bidet Intelligente",
    "Cane/Cagna", "Maial@", "Asin@", "Pavone", "Gatto", "Piatto", "Tazza", "Tram",
    "Cucchiaio", "Letto", "Doccia", "Sedia", "Frigorifero", "Cuscino", "Armadio", "Tavolo",
    "Zaino", "Libro", "Matita", "Cimice", "Ragno", "Formica", "Neve", "Fumo", "Nebbia",
    "Vento", "Fulmine", "Tuono", "Fango", "Erba", "Sabbia", "Terra", "Sasso", "Cemento",
    "Vite", "Chiodo", "Martello", "Scala", "Corda", "Specchio", "Orologio", "Quadro",
    "Pannello", "Secchio", "Serpente", "Muro", "Porta", "Finestra", "Tappeto", "Coperta",
    "Lavatrice", "Forno", "Bidet", "Cesso", "Lavandino", "Cassa", "Minestra",
    "Tiramisù", "Polpette", "Biscotto", "Caramella", "Crostata", "Pane", "Pizza", "Cicoria",
    "Insegna", "Semaforo", "Panchina", "Fontana", "Campanello", "Campana", "Statua",
    "Manichino", "Corriere", "Panettiere", "Barista", "Bagnino", "Tatuatore", "Magazziniere",
    "Programmatore", "Vigile", "Parrucchiere", "Pescatore", "Benzinaio", "Falegname",
    "Idraulico", "Giardiniere", "Muratore", "Camionista", "Spazzino", "Fabbro", "Contadino",
    "Postino", "Dinosauro", "Mummia", "Fantasma", "Cavaliere", "Merda",
    "Strega", "Vampiro", "Zombi", "Scheletro", "Alieno", "Robot", "Omino", "Bue", "Capra", "Pallone da Basket",
    "Puffo", "Yogurt alla Fragola", "Cavatappi", "Scatola di Cartone", "Maniglia", "Bottiglia d’Acqua",
    "Zebra", "Telecomando", "Macchina Fotografica", "Pannello Solare", "Biscottiera", "Limone",
    "Cacciavite", "Trivella", "Palo della Luce", "Semolino", "Spray Igienizzante", "Tenda da Campeggio",
    "Disco Volante", "Borsa Frigo", "Bancomat", "Cintura di Sicurezza", "Carrello della Spesa", "Proiettore",
    "AutoCAD", "Terremoto", "Sigma", "Chad", "Burundi", "Atmosfera", "Pianeta", "Gigante", "Trattore", "Televisione",
    "Polpettone", "Stagista", "Costumista", "Comunista", "Omosessuale", "Tendone", "Bastard@", "Dev-C++",
    "Volkswagen", "Schifos@", "fa schifo", "Ladr@", "Coglion@", "Maledett@", "Stronz@", "Cubo di Rubik",
    "Libro Scolastico", "Lurid@", "Sporc@", "Poster", "Torta di Fragole", "Congelat@", "Lampadario",
    "Sparacarote", "Tapparella", "Mensola", "Bisonte", "Dinosauro", "Milano", "Amsterdam", "Termosifone",
    "Albero di Natale", "Inutile", "Puzzolente", "Interruttore", "Post-it", "Gnomo", "Libreria", "Insetto",
    "Cavalluccio Marino", "Scaldabagno", "Vasca da Bagno", "Cuscino Termico", "Palloncino Bucato", "Pescepalla",
    "Cacciavite Esagonale", "Telo da Mare", "Infradito", "Rincoglionit@", "Addormentat@", "Addormentat@", "Scatenat@",
    "Strascatenat@", "Etichettatrice", "Fastidios@", "Sfulminat@", "Strasfulminat@", "Cretin@", "Spray Antizanzare",
    "Salvadanaio", "Idrossido di Sodio", "Idrossido di Potassio", "Cinese", "Montanar@", "Sparacazzate", "Agricoltore",
    "Raccolta Differenziata", "Toro", "LGBTQIA+", "Amazon Prime", "Testa di Cazzo", "Portatelefono", "Obes@",
    "Straobes@", "Straciccion@", "Ciccion@", "Organizer di Cavi", "Porc@", "Valigia", "Quercia", "Barcone",
    "Figura Retorica", "Equazione di 2° Grado", "Equazione", "Scatolone", "Cassetta Porta Attrezzi", "Carta di Credito",
    "Carta di Debito", "Contactless", "Bancomat", "Carta Regalo", "Vaso da Fiori", "Marciapiede", "Spalafieno",
    "Cavallo", "Posta Elettronica", "Appendiabiti", "Cappotto", "Portaombrelli", "Ignorante", "Pistacchio",
    "Fibra Ottica", "Sistema Solare", "Cassetto", "Password", "Foglio Protocollo", "Foglio A4", "Cartuccia per Stampanti",
    "Stran@", "Strastran@", "Data Center", "Database", "Autostrada", "Ricettario", "Sparamelanzane", "Tornado",
    "Troglodita", "Trigliceridi", "Colesterolo", "Fosfolipide", "Melone", "Vacca", "Straporc@", "Straboia",
    "Stramerda", "Straschifos@", "Straladr@", "Stracane", "Stratosferic@", "Pterodattilo", "Rinoceronte", "Elefante",
    "Automobile", "Macchina da Curire", "Macchina da Scrivere", "Stracretin@", "Stramaledett@", "Strastronz@",
    "Strabastard@", "Strasporc@", "Stralurid@", "Strafastidios@", "Strarincoglionit@", "Rompipalle", "Strarompipalle",
    "Ferro da Stiro", "Regione Veneto", "Venet@", "Ventilatore", "Pantofola", "Stracchino", "Prosciutto",
    "Prosciutto Cotto", "Prosciutto Crudo", "Speck", "Lampada a LED", "Rai 1", "Rai 2",
    "Cubo di Rubik", "Software di Editing", "Compressore ad'Aria", "Stampante 3D", "Casco da Minatore", "Scanner Laser",
    "Estintore", "Amplificatore WiFi", "Cuscino Cervicale", "Barattolo di Nutella", "Sveglia Digitale", "Termometro",
    "Motosega Elettrica", "Lente di Ingrandimento", "Tablet Rotto", "Tastiera Meccanica", "Simulatore di Volo",
    "Lava Pavimenti Automatico", "Controller PS5", "Luce LED RGB", "Occhiali VR", "Termometro a Infrarossi",
    "Piastra per Capelli", "Auricolari Bluetooth", "Zaino Antifurto", "Calcolatrice Scientifica", "Bidone Aspiratutto",
    "Rettangolare", "Ottaedro", "Proiezione Ortogonale", "Quadrato", "Triangolare", "Circolare", "Cubic@", "Strabic@",
    "Assonometria Isometrica", "Assonometria Cavaliera", "Assonometria Monometrica", "Pentagonale", "Pentagono",
    "Rettangolo", "Esagono", "Esagonale", "Ottagono", "Ottagonale", "Diedro", "Triedro", "Poliedro", "OGM", "Dodecagonale",
    "Decagonale", "Ettagonale", "Ettagono", "Emisfero Boreale", "Emisfero Australe", "Coste Frastagliate", "Vietnamita",
    "Pakistan@", "Azerbaijan@", "Tajikistan@", "Turkmenistan@", "Afghanistan@", "Uzbekistan@", "Kazakhstan@", "Kyrgyzstan@",
    "Insetticida", "Tappetino Yoga", "Lava Mani Automatico", "Asciugatore per Animali", "Tavoletta Grafica",
    "Speaker Smart", "Tenda Antivento", "Pannello LED Solare", "Barbecue Elettrico", "Contapassi Digitale",
    "Monitor Curvo", "Poltrona Massaggiante", "Ventilatore a Torre", "Spremiagrumi Elettrico", "Mouse Ergonomico",
    "Piantana LED", "Sottobicchiere Riscaldante", "Stampante Termica", "Box VR", "Drone con Telecamera",
    "Luce Notturna a Sensore", "Bottiglia Termica", "Mini Frigo USB", "Cornice Digitale", "Guanti Touchscreen",
    "Powerbank Solare", "Orologio Proiettore", "Supporto per Laptop", "Tagliere Intelligente", "Kit di Saldatura",
    "Termosmart", "Secchio a Pedale", "Contenitore Sottovuoto", "Multipresa Intelligente", "Cavo HDMI Flessibile",
    "Robot Aspirapolvere", "Fornello a Induzione", "Pad Riscaldante", "Umidificatore Portatile", "Specchio con LED",
    "Organizer da Scrivania", "Mini Videoproiettore", "Bilancia da Cucina", "Spazzolino Elettrico", "Forbici a Batteria",
    "Stampante per Etichette", "Torcia Dinamo", "Casco VR", "Friggitrice ad Aria", "Timer Magnetico", "Gancio da Porta",
    "Scatola Porta Cavi", "Pannello Fonoassorbente", "Lampada Antizanzare", "Pattumiera Intelligente",
    "Tritatutto Elettrico", "Poggiapolsi Ergonomico", "Pompa per Bici Elettrica", "Macchina per Popcorn",
    "Diffusore di Oli Essenziali", "Tappeto Antiscivolo", "Maniglia Intelligente", "Barra Magnetica",
    "Macchina per Bubble Tea", "Dispenser per Sapone", "Mini Lavatrice", "Lavapavimenti a Vapore",
    "Portaoggetti per Doccia", "Occhiali Intelligenti", "Radiolina Portatile", "Termocamera",
    "Cuscino Riscaldabile", "Mini Scaldapiedi", "Friggitrice Senza Olio", "Scaldapiedi", "5G Ultra Fold", "5G",
    "Wireless", "Sistema di Raffreddamento", "Conduzione Naturale", "Ombrellone", "eBook", "Email", "Costaricense",
    "Precipitevolissimevolmente", "Supercalifragilistichespiralidoso", "Mary Poppins", "Ciec@", "Segmento",
    "Banconota", "Moneta Metallica", "American Express", "Mastercard", "VISA", "Rai Sport", "Lurid@ Bastard@",
    "DOP", "Motore a Benzina", "Motore Diesel", "Motore 4 Tempi", "Motore 2 Tempi", "IGP", "TTRG", "Centrale Elettrica",
    "Atomo Biatomico Omonucleare", "Centrale Nucleare", "Nucleare", "Centrale Idroelettrica", "Pala Eolica",
    "Centrale Eolica", "Salame", "Mortadella", "McBoia", "McPorc@", "McSchifos@", "McLadr@", "Gran Crispy McBacon",
    "Insegnante", "Professore", "Bidone dell'Immondizia", "Obliteratrice", "Lavastoviglie", "Crostata", "Ministro",
    "Caricatore", "Cannone", "Scuola Superiore", "Scuola Media", "Incastrat@", "di Colore", "Torta Bicolore",
    "Ricarica Wireless", "Colla Stick", "Contapillole Digitale", "Tagliaunghie Laser", "Cuscino Antistress",
    "Cappello con Ventilatore", "Spazzola per Gatti", "Portachiavi GPS", "Cucchiaio Elettronico", "Apriscatole Robotico",
    "Portabicchieri da Auto", "Caricatore Wireless", "Penne 10 Colori", "Mini Aspirabriciole", "Calza Termica",
    "Forno Solare", "Pettine a Vibrazione", "Zerbino Interattivo", "Tenda a Scomparsa", "Piantana Multifunzione",
    "Tappetino Musicale", "Cintura Massaggiante", "Cubo Magnetico", "Portatovaglioli Intelligente", "Lama da Cucina Giroscopica",
    "Specchio da Borsetta LED", "Bicchiere Automescolante", "Tritaghiaccio Portatile", "Rasoio USB", "Luce da Lettura",
    "Taglierina Rotante", "Raffreddatore per Laptop", "Sedile Riscaldato", "Zaino Solare", "Cuffiette a Conduzione Ossea",
    "Stampante Portatile", "Macina Pepe Automatico", "Proiettore Galassia", "Porta Scarpe da Porta", "Termometro da Cucina",
    "Lente Macro per Smartphone", "Mini Idropulitrice", "Cavo 3 in 1", "Timer da Cucina Magnetico", "Luce da Bicicletta",
    "Campanello Smart", "Forchetta Pieghevole", "Asciugacapelli Silenzioso", "Lavagna Digitale", "Organizer da Valigia",
    "Lampada Lava", "Asciugamani Elettrico", "Spremi Tubetto", "Portadocumenti Magnetico", "Bracciolo Organizzatore",
    "Tavolo Regolabile", "Palla Antistress", "Occhiali Anti Luce Blu", "Tastiera Laser", "Rilevatore di Movimento",
    "Borsa Pieghevole", "Timer a Sabbia LED", "Scolapasta Intelligente", "Pistola per Colla a Caldo", "Termometro da Frigo",
    "Bilancia per Valigie", "Gancio per Borse", "Fischietto Ultrasuoni", "Mini Ventilatore USB",
    "Tazza Cambia Colore", "Cintura Portasoldi", "Pattumiera da Scrivania", "Contenitore per Snack", "Gancio per Sedili Auto",
    "Supporto per Cellulare", "Mini Frullatore", "Porta Tablet da Letto", "Mascherina con LED", "Lucchetto Smart",
    "Pettine per Barba", "Scolabottiglie", "Tazza con Altoparlante", "Telo Antipioggia", "Cuffie per Dormire",
    "Piastra Waffle", "Coperchio Universale", "Pulitore per Occhiali", "Set per SushI", "Tronchesine USB", "Diffusore Auto",
    "Scaldacollo USB", "Stazione Meteo Portatile", "Mini Vaporella", "Tappo per Bottiglie", "Adesivo Antiscivolo",
    "Cuscinetto per Mouse", "Pennarelli Sbiadenti", "Lente per Libro", "Gancio Appenditutto", "Pettine Anti Zanzare",
    "Supporto Anti Rollover", "Barra LED per Armadio", "Faccia da Merda", "Faccia da Culo", "Panettone", "Pandoro",
    "Chiave Inglese", "Pistone", "Cuscinetto a Sfere", "Frizione", "Albero Motore", "Rondella Dentata", "Mammut",
    "Canaglia", "Cancar@", "Cancaros@", "Reazione Chimica", "Furgoncino dei Gelati", "Camioncino dei Gelati", "Deodorante",
    "Soggetto Economico", "Kane/Kagna", "Vakka", "Vatican@", "Pork@", "Strapork@", "Kretin@", "Strakretin@",
    "Attestato di Partecipazione", "Burrocacao alla Menta", "Erba Aromatica", "Kankar@", "Strakankar@", "Stracancar@",
    "Kankaros@", "Strakankaros@", "Vatikan@", "Previsione del Meteo", "Tempo Meteorologico", "Skifos@", "Straskifos@",
    "Guardrail", "Merdos@", "Scanat@", "Incubatrice", "Costituzione Italiana", "Costituzione Americana", "Bengalese",
    "Indian@", "DNA", "Visual Studio Code", "Nicaraguense", "Antiguo-barbudan@", "Cuban@", "Atroce", "Bruciat@", "Suin@",
    "T-shirt", "T-rex", "Canestro", "Chihuahua", "Scimmia", "Avocado", "Gorilla", "Orangotango", "Pallavolista", "Bruschetta",
    "Cristoforo Colombo", "Homo Sapiens", "Australopiteco", "Bassotto", "Cocomero Marcio", "Anguria andata a Male",
    "Tagliatelle al Cinghiale", "Cinghiale", "Orso", "Pellerossa", "Postamat", "Carta Fedeltà", "NaCl", "Rotaia",
    "Gruppo Vacanze", "Swiffer", "Penna Scarica", "Penna Usata", "Pezzente", "Cover per Telefoni", "HTML", "CSS", "Alighieri",
    "Petrarca", "Boccaccio", "Tasso", "Leopardi", "Manzoni", "Pascoli", "Ungaretti", "Montale", "D'Annunzio", "Foscolo",
    "Carducci", "Cavolfiore", "Melanzana", "Pomodoro", "Cetriolo", "Finocchio", "Peperone", "Carota", "Zucchina", "Lattuga",
    "Radicchio", "Rucola", "Bietola", "Cipolla", "Aglio", "Broccolo", "Pisello", "Fagiolino", "Asparago", "Porro", "Sedano",
    "Rapa", "Zucca", "Barbabietola", "Cachi", "Mango", "Papaya", "Avocado", "Banana", "Fragola", "Anguria", "Melone", "Ciliegia",
    "Mela", "Pera", "Pesca", "Nettarina", "Albicocca", "Uva", "Ananas", "Kiwi", "Limone", "Mandarino", "Arancia", "Pompelmo",
    "Fico", "Melagrana", "Lampone", "Mirtillo", "Ribes", "More", "Tamarindo", "Carambola", "Litchi", "Noce", "Nocciola",
    "Mandorla", "Cocco", "Castagna", "Coccodrillo", "Pipistrello", "Alligatore", "Tirannosauro", "Paguro", "Canguro", "Cammello",
    "Ippopotamo", "Ornitorinco", "Fenicottero", "Pinguino", "Koala", "Giraffa", "Leone", "Tigre", "Lupo", "Volpe", "Scimmia",
    "Pantera", "Aquila", "Condor", "Falco", "Civetta", "Gufo", "Serpente", "Tartaruga", "Topo", "Ratto", "Talpa", "Castoro",
    "Scoiattolo", "Formichiere", "Bradipo", "Delfino", "Balena", "Squalo", "Medusa", "Polpo", "Calamaro", "Granchio",
    "Gambero", "Aragosta", "Riccio", "Stella Marina", "Cavalluccio Marino", "Corvo", "Cornacchia", "Gabbiano",
    "Piccione", "Passero", "Canarino", "Pappagallo", "Struzzo", "Emù", "Tacchino", "Gallina", "Gallo", "Anatra",
    "Oca", "Cigno", "Mosca", "Zanzara", "Ape", "Vespa", "Farfalla", "Cicala", "Coleottero", "Scarabeo", "Cavalletta",
    "Libellula", "Ragno", "Scorpione", "Lumaca", "Chiocciola", "Verme", "Larva", "Camaleonte", "Iguana", "Drago Barbuto",
    "Lucertola", "Gecko", "Salamandra", "Tritone", "Rospo", "Rana", "Anfisbena", "Colibrì", "Mangusta", "Tapiro", "Antenato",
    "Cervo", "Alce", "Gru", "Bue", "Bufalo", "Antilope", "Gnu", "Lama", "Pecora", "Capra", "Maiale", "Mucca", "Cavallo",
    "Asino", "Criceto", "Porcospino", "Toporagno", "Scoiattolo Volante", "Furetto", "Lontra", "Castoro", "Ghiro",
    "Uistitì", "Mandrillo", "Macaco", "Bonobo", "Gorilla", "Scimpanzé", "e i 7 nani", "Scaric@", "Discarica", "Pattumiera",
    "Acque Reflue", "Affluente", "Clown", "Orologio da Polso", "Orologio da Parete", "Sito Web", "Ventilatore Tascabile",
    "Liceo Scientifico", "Liceo Linguistico", "ITIS", "IPSIA", "Istituto Comprensivo Statale", "Statale", "Governo",
    "Frigorifero Tascabile", "Sbronz@", "Porchetta", "Ubriac@", "Astemi@", "Materasso Gonfiabile", "Materasso",
    "Pistola ad'Acqua", "Tostiera", "Bicicletta", "Confezionat@", "Industriale", "Allevamento Intensivo",
    "Cotoletta alla Bolognese", "Spaghetti alla Carbonara", "Pasta all'Amatriciana", "Pasticcio di Carne",
    "Polvere", "Cuscino Poggiapiedi", "Poggiapiedi", "Sparabestemmie", "COVID-19", "Ignorante", "Disabile", "Sottomarin@",
    "Acquatic@", "Pikachu", "Goku", "Aereo", "Aeroplano", "Cancello Automatico", "4 tempi", "2 tempi", "Portafiori"
];

// Genera bestemmia
function generaBestemmia() {
    document.getElementById("bestemmia").textContent = `${soggetti[Math.floor(Math.random() * soggetti.length)]} ${oggetti[Math.floor(Math.random() * oggetti.length)]}`;
}

// Contatore bestemmie
document.getElementById("contatore").textContent = soggetti.length * oggetti.length;